import { MenuItem, RestaurantTable, WeeklyScheduleDay, ScheduleOverride, RestaurantSettings, Reservation } from "./types";

export const INITIAL_SETTINGS: RestaurantSettings = {
  restaurant_name: "L'Union Pizza",
  phone: "+62 852-2609-9883",
  whatsapp: "0852-2609-9883",
  booking_fee: 10000,
  payment_bank: "SeaBank",
  payment_account: "901702376579",
  account_name: "L'Union Pizza MYO",
  address: "Jl. Veteran No. 42, Artisan Dining Quarter",
  maps_url: "https://maps.google.com/?q=LUnion+Pizza",
};

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: "menu-1",
    name: "Margherita",
    slug: "margherita",
    description: "San Marzano tomatoes, fresh Fior di Latte mozzarella, fragrant sweet basil, extra virgin olive oil.",
    price: 58000,
    image: "https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 1,
    tags: ["Classic", "Vegetarian"],
  },
  {
    id: "menu-2",
    name: "Primavera",
    slug: "primavera",
    description: "Sun-dried tomatoes, tender artichoke hearts, baby spinach, roasted garlic, fior di latte.",
    price: 67000,
    image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 2,
    tags: ["Vegetarian", "Garden Fresh"],
  },
  {
    id: "menu-3",
    name: "Aloha",
    slug: "aloha",
    description: "Caramelized sweet pineapple, premium smoked ham, rich tomato sugo, molten mozzarella.",
    price: 80000,
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 3,
    tags: ["Signature", "Sweet & Savory"],
  },
  {
    id: "menu-4",
    name: "Pepperoni",
    slug: "pepperoni",
    description: "Spicy artisan beef pepperoni, crushed chili flakes, rich red sauce, mozzarella di bufala.",
    price: 67000,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 4,
    tags: ["Best Seller", "Spicy"],
  },
  {
    id: "menu-5",
    name: "Proteinata",
    slug: "proteinata",
    description: "Slow-roasted pulled chicken breast, crisp beef bacon crisps, soft egg swirl, fresh ricotta.",
    price: 90000,
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 5,
    tags: ["High Protein", "Savory"],
  },
  {
    id: "menu-6",
    name: "Quattro Fromaggi",
    slug: "quattro-fromaggi",
    description: "A decadent harmony of Gorgonzola dolce, aged Parmigiano-Reggiano, smoked provolone, creamy fior di latte.",
    price: 113000,
    image: "https://images.unsplash.com/photo-1573821663912-569905455b1c?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 6,
    tags: ["Chef Special", "Cheese Lovers"],
  },
  {
    id: "menu-7",
    name: "Beef Royale",
    slug: "beef-royale",
    description: "Wagyu minced beef ragu, caramelized red onions, sautéed portobello mushrooms, truffle essence drizzle.",
    price: 97000,
    image: "https://images.unsplash.com/photo-1541745537411-b8046dc6d66c?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 7,
    tags: ["Gourmet", "Truffle"],
  },
  {
    id: "menu-8",
    name: "Meatza",
    slug: "meatza",
    description: "The ultimate carnivore feast: pepperoni, Italian sausage crumble, smoked beef slices, spicy marinara.",
    price: 85000,
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 8,
    tags: ["Hearty", "Meaty"],
  },
  {
    id: "menu-9",
    name: "Le Jardin",
    slug: "le-jardin",
    description: "Grilled zucchini ribbons, marinated bell peppers, Kalamata olives, whipped goat cheese, fresh oregano.",
    price: 75000,
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 9,
    tags: ["Vegetarian", "Mediterranean"],
  },
];

export const INITIAL_TABLES: RestaurantTable[] = [
  {
    id: "table-napoli",
    name: "Napoli",
    description: "Front-row hearthside table with a direct view of our roaring wood-fired stone oven. Intimate warm glow.",
    image_url: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 1,
    capacity: 4,
  },
  {
    id: "table-romana",
    name: "Romana",
    description: "Cozy leather-boothed corner table under warm architectural pendants, perfect for relaxed crafting.",
    image_url: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    is_active: true,
    sort_order: 2,
    capacity: 4,
  },
];

export const INITIAL_WEEKLY_SCHEDULE: WeeklyScheduleDay[] = [
  { id: "ws-0", day_of_week: 0, day_name: "Sunday", is_open: true, start_time: "11:00", end_time: "21:00", interval_minutes: 15 },
  { id: "ws-1", day_of_week: 1, day_name: "Monday", is_open: true, start_time: "11:00", end_time: "21:00", interval_minutes: 15 },
  { id: "ws-2", day_of_week: 2, day_name: "Tuesday", is_open: true, start_time: "11:00", end_time: "21:00", interval_minutes: 15 },
  { id: "ws-3", day_of_week: 3, day_name: "Wednesday", is_open: true, start_time: "11:00", end_time: "21:00", interval_minutes: 15 },
  { id: "ws-4", day_of_week: 4, day_name: "Thursday", is_open: true, start_time: "11:00", end_time: "21:00", interval_minutes: 15 },
  { id: "ws-5", day_of_week: 5, day_name: "Friday", is_open: true, start_time: "14:00", end_time: "21:00", interval_minutes: 15 },
  { id: "ws-6", day_of_week: 6, day_name: "Saturday", is_open: true, start_time: "11:00", end_time: "21:00", interval_minutes: 15 },
];

export const INITIAL_OVERRIDES: ScheduleOverride[] = [
  {
    id: "ovr-1",
    date: "2026-12-24",
    is_open: true,
    start_time: "11:00",
    end_time: "18:00",
    interval_minutes: 15,
    note: "Christmas Eve Special Hours",
  },
  {
    id: "ovr-2",
    date: "2026-12-25",
    is_open: false,
    start_time: "11:00",
    end_time: "21:00",
    interval_minutes: 15,
    note: "Closed for Christmas Celebration",
  },
];

// Helper to get formatted date string for today and future days
export function getFormattedDateOffset(daysOffset = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: "res-1",
    code: "MYO-B8X12",
    date: getFormattedDateOffset(0), // Today
    time: "12:00",
    table_id: "table-napoli",
    table_name: "Napoli",
    customer_name: "Aditya Pratama",
    customer_whatsapp: "081234567890",
    pax: 2,
    note: "Window view if possible, celebrating anniversary!",
    is_special_kreasi: false,
    menu_item_id: "menu-4",
    menu_name: "Pepperoni",
    total_product_price: 67000,
    booking_fee: 10000,
    payment_proof_url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
    payment_proof_name: "bukti-transfer-seabank.jpg",
    status: "CONFIRMED",
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: "res-2",
    code: "MYO-C9Z34",
    date: getFormattedDateOffset(0), // Today
    time: "12:15",
    table_id: "table-romana",
    table_name: "Romana",
    customer_name: "Clarissa Wijaya",
    customer_whatsapp: "081987654321",
    pax: 3,
    note: "Extra crispy crust please",
    is_special_kreasi: true,
    flavor_1_id: "menu-1",
    flavor_1_name: "Margherita",
    flavor_1_price: 58000,
    flavor_2_id: "menu-6",
    flavor_2_name: "Quattro Fromaggi",
    flavor_2_price: 113000,
    total_product_price: 85500, // (58000 + 113000)/2
    booking_fee: 10000,
    payment_proof_url: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80",
    payment_proof_name: "seabank_10k.png",
    status: "PENDING",
    created_at: new Date(Date.now() - 1800000).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "res-3",
    code: "MYO-D2Y78",
    date: getFormattedDateOffset(0), // Today
    time: "13:00",
    table_id: "table-napoli",
    table_name: "Napoli",
    customer_name: "Budi Santoso",
    customer_whatsapp: "08551234998",
    pax: 2,
    is_special_kreasi: false,
    menu_item_id: "menu-7",
    menu_name: "Beef Royale",
    total_product_price: 97000,
    booking_fee: 10000,
    payment_proof_url: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600&auto=format&fit=crop&q=80",
    payment_proof_name: "transfer_proof.jpg",
    status: "REJECTED",
    rejection_reason: "Bukti transfer tidak terbaca / nominal tidak sesuai.",
    created_at: new Date(Date.now() - 7200000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "res-4",
    code: "MYO-F4K91",
    date: getFormattedDateOffset(1), // Tomorrow
    time: "18:00",
    table_id: "table-napoli",
    table_name: "Napoli",
    customer_name: "Jessica Tan",
    customer_whatsapp: "081299887766",
    pax: 4,
    note: "Family gathering MYO",
    is_special_kreasi: true,
    flavor_1_id: "menu-3",
    flavor_1_name: "Aloha",
    flavor_1_price: 80000,
    flavor_2_id: "menu-4",
    flavor_2_name: "Pepperoni",
    flavor_2_price: 67000,
    total_product_price: 73500, // (80000 + 67000)/2
    booking_fee: 10000,
    payment_proof_url: "https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=600&auto=format&fit=crop&q=80",
    payment_proof_name: "seabank-proof.jpg",
    status: "CONFIRMED",
    created_at: new Date(Date.now() - 14400000).toISOString(),
    updated_at: new Date(Date.now() - 7200000).toISOString(),
  }
];
